TempStr = int(input())
if TempStr == 0:
    print("Hello World")
elif TempStr > 0:
    print("He")
    print("ll")
    print("o ")
    print("Wo")
    print("rl")
    print("d")
else:
    print("H")
    print("e")
    print("l")
    print("l")
    print("o")
    print(" ")
    print("W")
    print("o")
    print("r")
    print("l")
    print("d")